name = "TupleLabXD"
uuid = "dd89015c-70e0-43f5-a84b-ae32a3a24356"
authors = ["PhysicsCodesLab"]
version = "0.1.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
